server.port: 8002

spring:
  application.name: microsvc-service
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        instanceId: service_0
        serviceName: service
        hostname: localhost
        port: ${server.port}
        healthCheckUrl: http://${spring.cloud.consul.discovery.hostname}:${server.port}/actuator/health
        healthCheckInterval: 10s
        tags: dev

logging:
  level.org.springframework.web: DEBUG
  # Adds trace and span IDs to logs (when a trace is in progress)
  pattern.level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}]%-5p [%t] %C{2} - %m%n'
