server:
  port: 8001

spring:
  application.name: microsvc-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        instanceId: gateway_0
        serviceName: gateway
        hostname: localhost
        port: ${server.port}
        healthCheckUrl: http://${spring.cloud.consul.discovery.hostname}:${server.port}/actuator/health
        healthCheckInterval: 10s
        tags: dev
    gateway:
      routes:
        - id: service-websocket
          uri: lb://service
          order: 9000
          predicates:
            - Path=/ws/**
          filters:
              - StripPrefix=1
        - id: service
          uri: lb://service
          order: 8000
          predicates:
            - Path=/service/**
          filters:
              - StripPrefix=1


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
